### PR TITLE
Update to Grails 6 (v5.0.0)

### PR DESCRIPTION
**Pull request by matrei**
Compatible with Groovy 3.0.19
Updated gradle build to use version catalogs
Added renovate and dependabot
Documentation generation has been disabled. Maybe create a separate project for documentation like grails/grails-data-mapping -> grails/gorm-docs

### CODE REVIEW

**Comment by matrei** [comment]
@puneetbehl Please review

**Comment by puneetbehl** [comment]
Is there a reason to not publish documentation in here anymore?

**Comment by matrei** [comment]
No, not really. I don't know why it was done that way in the grails-data-mapping, so I wanted to ask if that was the way to do it going forward.

**Comment by matrei** [comment]
Resolves #35

**Pull request merged**
